apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type}}
